services:
  liferay:
    container_name: liferay
    image: liferay/portal:7.4.3.100-ga100
    ports:
      - "8080:8080"
    environment:
      - LIFERAY_JAVA_OPTS=-Djava.version=11
      - LIFERAY_DB_HOST=mysql
      - LIFERAY_DB_PORT=3306
      - LIFERAY_DB_NAME=liferay
      - LIFERAY_DB_USER=liferay
      - LIFERAY_DB_PASSWORD=liferay
    depends_on:
      - mysql
    volumes:
      - ./portal-ext.properties:/opt/liferay/portal-ext.properties
      - ./deploy:/opt/liferay/deploy      
      - ./data:/opt/liferay/data
      - ./osgi-state:/opt/liferay/osgi/state

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: liferay
      MYSQL_USER: liferay
      MYSQL_PASSWORD: liferay
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
